# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# relative permalinks removed in jekyll 3.0
relative_permalinks: false

# Setup
title:            eoa
tagline:          'Eye of Agamotto'
description:      'The blog of John Griffiths, <a href="https://twitter.com/johnantoni" target="_blank">@johnantoni</a>.'
url:              http://eyeofagamotto.ca
baseurl:          /

author:
  name:           'John Griffiths'
  url:            https://twitter.com/johnantoni

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/johnantoni/eyeofagamotto.git

gems:             [jekyll-paginate, jekyll-gist, pygments.rb, kramdown]